game_list = ['nintendo','sony','sega']
print(f"You have {len(game_list)} item in your")
print(f"{game_list}")
print("-------------------------------------------------------------")
guest_revok = 'sega'
game_list.remove(guest_revok)
game_list.append('master system')
print(f"{game_list}")
print("-------------------------------------------------------------")
game_list.insert(0,'playstation')
game_list.insert(2,'neogeo')
game_list.append('switch')
print(f"{game_list}")
print("-------------------------------------------------------------")
del game_list[1]
print(f"{game_list}")
print("-------------------------------------------------------------")
print(sorted(game_list))
print(game_list)
print("-------------------------------------------------------------")
print(sorted(game_list,reverse=True))
print(game_list)
print("-------------------------------------------------------------")
game_list.reverse()
print(game_list)
print("-------------------------------------------------------------")
game_list.reverse()
print(game_list)
print("-------------------------------------------------------------")
game_list.sort()
print(game_list)
print("-------------------------------------------------------------")
game_list.sort(reverse=True)
print(game_list)
print(f"You have {len(game_list)} item in your")


